# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Andrea Diecidue/Documents/GitHub/GameZero/moving_characters/moving_characters.srcs/sources_1/ip/BROM_Pedana/BROM_Pedana.xci
# IP: The module: 'BROM_Pedana' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Documents/GitHub/GameZero/moving_characters/moving_characters.srcs/sources_1/ip/BROM_Pedana/BROM_Pedana_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BROM_Pedana'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Andrea Diecidue/Documents/GitHub/GameZero/moving_characters/moving_characters.srcs/sources_1/ip/BROM_Pedana/BROM_Pedana.xci
# IP: The module: 'BROM_Pedana' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Documents/GitHub/GameZero/moving_characters/moving_characters.srcs/sources_1/ip/BROM_Pedana/BROM_Pedana_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BROM_Pedana'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
