# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.xci
# IP: The module: 'BRAM_VGA_Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.xci
# IP: The module: 'BRAM_VGA_Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_VGA_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
