# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/Wolvie_BROM/Wolvie_BROM.xci
# IP: The module: 'Wolvie_BROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/Wolvie_BROM/Wolvie_BROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wolvie_BROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/Wolvie_BROM/Wolvie_BROM.xci
# IP: The module: 'Wolvie_BROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/Wolvie_BROM/Wolvie_BROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wolvie_BROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
