# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/utilBROM/utilBROM.xci
# IP: The module: 'utilBROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/utilBROM/utilBROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'utilBROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/utilBROM/utilBROM.xci
# IP: The module: 'utilBROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/utilBROM/utilBROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'utilBROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
