# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock.xci
# IP: The module: 'controller_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock.xci
# IP: The module: 'controller_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/controller_project/controller_project.srcs/sources_1/ip/controller_clock/controller_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
