# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.cache/wt [current_project]
set_property parent.project_path C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.dcp
set_property used_in_implementation false [get_files C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/ip/BRAM_VGA_Clock/BRAM_VGA_Clock.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/new/RAM_VGA.vhd
  C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/new/vga.vhd
  C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/sources_1/new/Graphics.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/constrs_1/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/edoardo/Documents/GitHub/GameZero/GameZero/GameZero.srcs/constrs_1/Nexys4_Master.xdc]


synth_design -top Graphics -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Graphics.dcp

catch { report_utilization -file Graphics_utilization_synth.rpt -pb Graphics_utilization_synth.pb }
