# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen.xci
# IP: The module: 'PixelClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen.xci
# IP: The module: 'PixelClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Andrea Diecidue/Desktop/polito/Computer Architecture/Projects/vga/vga.srcs/sources_1/ip/PixelClkGen/PixelClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
