# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen.xci
# IP: The module: 'pixelClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen.xci
# IP: The module: 'pixelClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/edoardo/GameZero/GameZero.srcs/sources_1/ip/pixelClkGen/pixelClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
